py -m pip install -i https://pypi.tuna.tsinghua.edu.cn/simple pip==23.2
py -m pip install -i https://pypi.tuna.tsinghua.edu.cn/simple akshare
py -m pip install -i https://pypi.tuna.tsinghua.edu.cn/simple easyquotation
py -m pip install -i https://pypi.tuna.tsinghua.edu.cn/simple yagmail
py -m pip install -i https://pypi.tuna.tsinghua.edu.cn/simple pywinauto==0.6.6
py -m pip install -i https://pypi.tuna.tsinghua.edu.cn/simple matplotlib
py -m pip install -i https://pypi.tuna.tsinghua.edu.cn/simple mplfinance
py -m pip install -i https://pypi.tuna.tsinghua.edu.cn/simple finta
py -m pip install -i https://pypi.tuna.tsinghua.edu.cn/simple pyinstaller
py -m pip install -i https://pypi.tuna.tsinghua.edu.cn/simple pyautogui
py -m pip install -i https://pypi.tuna.tsinghua.edu.cn/simple schedule
py -m pip install -i https://pypi.tuna.tsinghua.edu.cn/simple pywin32
py -m pip install -i https://pypi.tuna.tsinghua.edu.cn/simple pyexecjs
py -m pip install -i https://pypi.tuna.tsinghua.edu.cn/simple pytdx
py -m pip install -i https://pypi.tuna.tsinghua.edu.cn/simple pydash